import Head from 'next/head'
import { Button, Card, CardActions, CardContent, CssBaseline } from '@mui/material'

export default function Home() {

  return (
    <>
      <Head>
        <title>Чкалов.Типография</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Card>
          <CardContent style={{fontFamily: 'Raleway'}}>
            Hello
          </CardContent>
          <CardActions>
            <Button>Hello</Button>
            <Button variant='contained'>Hello</Button>
          </CardActions>
        </Card>
      </main>
    </>
  )
}
